name: Prettier Auto‑Fix

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  prettier-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Prettier Fix
        uses: WorkOfStan/prettier-fix@v1.1.5
        with:
          commit-changes: true
          commit-message: "style(prettier): auto-format code via CI pipeline"
